// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fastPLS.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include "r_api.h"

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cuda_resident_project_cpp
SEXP cuda_resident_project_cpp(Rcpp::List object, SEXP X, int ncomp);
RcppExport SEXP _fastPLS_cuda_resident_project_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_resident_project_cpp(object, X, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// cuda_resident_response_sums_cpp
SEXP cuda_resident_response_sums_cpp(Rcpp::List object, SEXP X, SEXP Y, SEXP labels, int ncomp);
RcppExport SEXP _fastPLS_cuda_resident_response_sums_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP YSEXP, SEXP labelsSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_resident_response_sums_cpp(object, X, Y, labels, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// cuda_resident_simpls_fit_cpp
Rcpp::List cuda_resident_simpls_fit_cpp(SEXP X, SEXP Y, SEXP labels, int classes, int precision, int ncomp, int scaling, int oversample, int power, int seed, bool retain_scores, int method, int north, int kernel, double gamma, int degree, double coef0);
RcppExport SEXP _fastPLS_cuda_resident_simpls_fit_cpp(SEXP XSEXP, SEXP YSEXP, SEXP labelsSEXP, SEXP classesSEXP, SEXP precisionSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP oversampleSEXP, SEXP powerSEXP, SEXP seedSEXP, SEXP retain_scoresSEXP, SEXP methodSEXP, SEXP northSEXP, SEXP kernelSEXP, SEXP gammaSEXP, SEXP degreeSEXP, SEXP coef0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type classes(classesSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type oversample(oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type power(powerSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type retain_scores(retain_scoresSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type north(northSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_resident_simpls_fit_cpp(X, Y, labels, classes, precision, ncomp, scaling, oversample, power, seed, retain_scores, method, north, kernel, gamma, degree, coef0));
    return rcpp_result_gen;
END_RCPP
}
// cuda_resident_export_cpp
Rcpp::List cuda_resident_export_cpp(Rcpp::List object, bool loadings, bool variance, bool scores);
RcppExport SEXP _fastPLS_cuda_resident_export_cpp(SEXP objectSEXP, SEXP loadingsSEXP, SEXP varianceSEXP, SEXP scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< bool >::type loadings(loadingsSEXP);
    Rcpp::traits::input_parameter< bool >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< bool >::type scores(scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_resident_export_cpp(object, loadings, variance, scores));
    return rcpp_result_gen;
END_RCPP
}
// cuda_resident_compact_cpp
void cuda_resident_compact_cpp(Rcpp::List object, bool prepare_lda);
RcppExport SEXP _fastPLS_cuda_resident_compact_cpp(SEXP objectSEXP, SEXP prepare_ldaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< bool >::type prepare_lda(prepare_ldaSEXP);
    cuda_resident_compact_cpp(object, prepare_lda);
    return R_NilValue;
END_RCPP
}
// cuda_resident_classify_cpp
Rcpp::IntegerMatrix cuda_resident_classify_cpp(Rcpp::List object, SEXP X, int ncomp, int classifier, int top);
RcppExport SEXP _fastPLS_cuda_resident_classify_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP, SEXP classifierSEXP, SEXP topSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    Rcpp::traits::input_parameter< int >::type top(topSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_resident_classify_cpp(object, X, ncomp, classifier, top));
    return rcpp_result_gen;
END_RCPP
}
// cuda_resident_classify_path_cpp
Rcpp::IntegerVector cuda_resident_classify_path_cpp(Rcpp::List object, SEXP X, Rcpp::IntegerVector ncomp, int classifier, int top);
RcppExport SEXP _fastPLS_cuda_resident_classify_path_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP, SEXP classifierSEXP, SEXP topSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    Rcpp::traits::input_parameter< int >::type top(topSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_resident_classify_path_cpp(object, X, ncomp, classifier, top));
    return rcpp_result_gen;
END_RCPP
}
// cuda_resident_classify_response_path_cpp
Rcpp::List cuda_resident_classify_response_path_cpp(Rcpp::List object, SEXP X, Rcpp::IntegerVector ncomp, int classifier, int top);
RcppExport SEXP _fastPLS_cuda_resident_classify_response_path_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP, SEXP classifierSEXP, SEXP topSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    Rcpp::traits::input_parameter< int >::type top(topSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_resident_classify_response_path_cpp(object, X, ncomp, classifier, top));
    return rcpp_result_gen;
END_RCPP
}
// cuda_resident_simpls_predict_cpp
SEXP cuda_resident_simpls_predict_cpp(Rcpp::List object, SEXP X, int ncomp, int classifier);
RcppExport SEXP _fastPLS_cuda_resident_simpls_predict_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP, SEXP classifierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_resident_simpls_predict_cpp(object, X, ncomp, classifier));
    return rcpp_result_gen;
END_RCPP
}
// cuda_resident_predict_path_cpp
SEXP cuda_resident_predict_path_cpp(Rcpp::List object, SEXP X, Rcpp::IntegerVector ncomp, int classifier);
RcppExport SEXP _fastPLS_cuda_resident_predict_path_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP, SEXP classifierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_resident_predict_path_cpp(object, X, ncomp, classifier));
    return rcpp_result_gen;
END_RCPP
}
// rsvd_audit_reset_debug
void rsvd_audit_reset_debug();
RcppExport SEXP _fastPLS_rsvd_audit_reset_debug() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    rsvd_audit_reset_debug();
    return R_NilValue;
END_RCPP
}
// rsvd_audit_summary_debug
Rcpp::List rsvd_audit_summary_debug();
RcppExport SEXP _fastPLS_rsvd_audit_summary_debug() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rsvd_audit_summary_debug());
    return rcpp_result_gen;
END_RCPP
}
// label_crossprod_scaled_cpp
List label_crossprod_scaled_cpp(SEXP XtrainSEXP, Rcpp::IntegerVector y, int n_classes, int scaling);
RcppExport SEXP _fastPLS_label_crossprod_scaled_cpp(SEXP XtrainSEXPSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP scalingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XtrainSEXP(XtrainSEXPSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    rcpp_result_gen = Rcpp::wrap(label_crossprod_scaled_cpp(XtrainSEXP, y, n_classes, scaling));
    return rcpp_result_gen;
END_RCPP
}
// float32_sweep_cols_cpp
Rcpp::IntegerMatrix float32_sweep_cols_cpp(SEXP XSEXP, SEXP rowSEXP, int operation);
RcppExport SEXP _fastPLS_float32_sweep_cols_cpp(SEXP XSEXPSEXP, SEXP rowSEXPSEXP, SEXP operationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type XSEXP(XSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rowSEXP(rowSEXPSEXP);
    Rcpp::traits::input_parameter< int >::type operation(operationSEXP);
    rcpp_result_gen = Rcpp::wrap(float32_sweep_cols_cpp(XSEXP, rowSEXP, operation));
    return rcpp_result_gen;
END_RCPP
}
// float32_standardize_cpp
Rcpp::IntegerMatrix float32_standardize_cpp(SEXP XSEXP, SEXP centerSEXP, SEXP scaleSEXP);
RcppExport SEXP _fastPLS_float32_standardize_cpp(SEXP XSEXPSEXP, SEXP centerSEXPSEXP, SEXP scaleSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type XSEXP(XSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type centerSEXP(centerSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type scaleSEXP(scaleSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(float32_standardize_cpp(XSEXP, centerSEXP, scaleSEXP));
    return rcpp_result_gen;
END_RCPP
}
// kernel_matrix_float32_cpp
Rcpp::List kernel_matrix_float32_cpp(SEXP X1SEXP, SEXP X2SEXP, int kernel, double gamma, int degree, double coef0, int backend);
RcppExport SEXP _fastPLS_kernel_matrix_float32_cpp(SEXP X1SEXPSEXP, SEXP X2SEXPSEXP, SEXP kernelSEXP, SEXP gammaSEXP, SEXP degreeSEXP, SEXP coef0SEXP, SEXP backendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X1SEXP(X1SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X2SEXP(X2SEXPSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    Rcpp::traits::input_parameter< int >::type backend(backendSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_matrix_float32_cpp(X1SEXP, X2SEXP, kernel, gamma, degree, coef0, backend));
    return rcpp_result_gen;
END_RCPP
}
// center_kernel_train_float32_cpp
Rcpp::List center_kernel_train_float32_cpp(SEXP KSEXP);
RcppExport SEXP _fastPLS_center_kernel_train_float32_cpp(SEXP KSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type KSEXP(KSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(center_kernel_train_float32_cpp(KSEXP));
    return rcpp_result_gen;
END_RCPP
}
// center_kernel_test_float32_cpp
Rcpp::List center_kernel_test_float32_cpp(SEXP KtestSEXP, SEXP trainColMeansSEXP, double train_grand_mean);
RcppExport SEXP _fastPLS_center_kernel_test_float32_cpp(SEXP KtestSEXPSEXP, SEXP trainColMeansSEXPSEXP, SEXP train_grand_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type KtestSEXP(KtestSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trainColMeansSEXP(trainColMeansSEXPSEXP);
    Rcpp::traits::input_parameter< double >::type train_grand_mean(train_grand_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(center_kernel_test_float32_cpp(KtestSEXP, trainColMeansSEXP, train_grand_mean));
    return rcpp_result_gen;
END_RCPP
}
// opls_filter_float32_cpp
Rcpp::List opls_filter_float32_cpp(SEXP XSEXP, SEXP YSEXP, int north, int scaling, int backend, int svd_method, int rsvd_oversample, int rsvd_power, int seed);
RcppExport SEXP _fastPLS_opls_filter_float32_cpp(SEXP XSEXPSEXP, SEXP YSEXPSEXP, SEXP northSEXP, SEXP scalingSEXP, SEXP backendSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XSEXP(XSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YSEXP(YSEXPSEXP);
    Rcpp::traits::input_parameter< int >::type north(northSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(opls_filter_float32_cpp(XSEXP, YSEXP, north, scaling, backend, svd_method, rsvd_oversample, rsvd_power, seed));
    return rcpp_result_gen;
END_RCPP
}
// opls_filter_float32_labels_cpp
Rcpp::List opls_filter_float32_labels_cpp(SEXP XSEXP, const Rcpp::IntegerVector& labels, int n_classes, int north, int scaling, int backend, int svd_method, int rsvd_oversample, int rsvd_power, int seed);
RcppExport SEXP _fastPLS_opls_filter_float32_labels_cpp(SEXP XSEXPSEXP, SEXP labelsSEXP, SEXP n_classesSEXP, SEXP northSEXP, SEXP scalingSEXP, SEXP backendSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XSEXP(XSEXPSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< int >::type north(northSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(opls_filter_float32_labels_cpp(XSEXP, labels, n_classes, north, scaling, backend, svd_method, rsvd_oversample, rsvd_power, seed));
    return rcpp_result_gen;
END_RCPP
}
// opls_apply_filter_float32_cpp
Rcpp::List opls_apply_filter_float32_cpp(SEXP XSEXP, SEXP mXSEXP, SEXP vXSEXP, SEXP WSEXP, SEXP PSEXP, int backend);
RcppExport SEXP _fastPLS_opls_apply_filter_float32_cpp(SEXP XSEXPSEXP, SEXP mXSEXPSEXP, SEXP vXSEXPSEXP, SEXP WSEXPSEXP, SEXP PSEXPSEXP, SEXP backendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XSEXP(XSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mXSEXP(mXSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vXSEXP(vXSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type WSEXP(WSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type PSEXP(PSEXPSEXP);
    Rcpp::traits::input_parameter< int >::type backend(backendSEXP);
    rcpp_result_gen = Rcpp::wrap(opls_apply_filter_float32_cpp(XSEXP, mXSEXP, vXSEXP, WSEXP, PSEXP, backend));
    return rcpp_result_gen;
END_RCPP
}
// lda_train_prefix_float32_cpp
Rcpp::List lda_train_prefix_float32_cpp(SEXP TtrainSEXP, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp);
RcppExport SEXP _fastPLS_lda_train_prefix_float32_cpp(SEXP TtrainSEXPSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type TtrainSEXP(TtrainSEXPSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_train_prefix_float32_cpp(TtrainSEXP, y, n_classes, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_float32_cpp
Rcpp::List lda_predict_float32_cpp(SEXP TtestSEXP, const Rcpp::List& lda, bool return_scores);
RcppExport SEXP _fastPLS_lda_predict_float32_cpp(SEXP TtestSEXPSEXP, SEXP ldaSEXP, SEXP return_scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type TtestSEXP(TtestSEXPSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    Rcpp::traits::input_parameter< bool >::type return_scores(return_scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_float32_cpp(TtestSEXP, lda, return_scores));
    return rcpp_result_gen;
END_RCPP
}
// lda_train_prefix_float32_cuda
Rcpp::List lda_train_prefix_float32_cuda(SEXP TtrainSEXP, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp);
RcppExport SEXP _fastPLS_lda_train_prefix_float32_cuda(SEXP TtrainSEXPSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type TtrainSEXP(TtrainSEXPSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_train_prefix_float32_cuda(TtrainSEXP, y, n_classes, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_float32_cuda
Rcpp::List lda_predict_float32_cuda(SEXP TtestSEXP, const Rcpp::List& lda, bool return_scores);
RcppExport SEXP _fastPLS_lda_predict_float32_cuda(SEXP TtestSEXPSEXP, SEXP ldaSEXP, SEXP return_scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type TtestSEXP(TtestSEXPSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    Rcpp::traits::input_parameter< bool >::type return_scores(return_scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_float32_cuda(TtestSEXP, lda, return_scores));
    return rcpp_result_gen;
END_RCPP
}
// cuda_float32_rsvd_sample_cpp
Rcpp::List cuda_float32_rsvd_sample_cpp(SEXP ASEXP, int l, int power_iters, int seed);
RcppExport SEXP _fastPLS_cuda_float32_rsvd_sample_cpp(SEXP ASEXPSEXP, SEXP lSEXP, SEXP power_itersSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ASEXP(ASEXPSEXP);
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< int >::type power_iters(power_itersSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_float32_rsvd_sample_cpp(ASEXP, l, power_iters, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpu_float32_matrix_multiply_cpp
Rcpp::List cpu_float32_matrix_multiply_cpp(SEXP ASEXP, SEXP BSEXP, bool transpose_left, bool transpose_right);
RcppExport SEXP _fastPLS_cpu_float32_matrix_multiply_cpp(SEXP ASEXPSEXP, SEXP BSEXPSEXP, SEXP transpose_leftSEXP, SEXP transpose_rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ASEXP(ASEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type BSEXP(BSEXPSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose_left(transpose_leftSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose_right(transpose_rightSEXP);
    rcpp_result_gen = Rcpp::wrap(cpu_float32_matrix_multiply_cpp(ASEXP, BSEXP, transpose_left, transpose_right));
    return rcpp_result_gen;
END_RCPP
}
// metal_float32_matrix_multiply_cpp
Rcpp::List metal_float32_matrix_multiply_cpp(SEXP ASEXP, SEXP BSEXP, bool transpose_left, bool transpose_right);
RcppExport SEXP _fastPLS_metal_float32_matrix_multiply_cpp(SEXP ASEXPSEXP, SEXP BSEXPSEXP, SEXP transpose_leftSEXP, SEXP transpose_rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ASEXP(ASEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type BSEXP(BSEXPSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose_left(transpose_leftSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose_right(transpose_rightSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_float32_matrix_multiply_cpp(ASEXP, BSEXP, transpose_left, transpose_right));
    return rcpp_result_gen;
END_RCPP
}
// metal_float32_rsvd_sample_cpp
Rcpp::List metal_float32_rsvd_sample_cpp(SEXP ASEXP, int l, int power_iters, int seed);
RcppExport SEXP _fastPLS_metal_float32_rsvd_sample_cpp(SEXP ASEXPSEXP, SEXP lSEXP, SEXP power_itersSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ASEXP(ASEXPSEXP);
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< int >::type power_iters(power_itersSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_float32_rsvd_sample_cpp(ASEXP, l, power_iters, seed));
    return rcpp_result_gen;
END_RCPP
}
// fastsvd_float32_cpp
Rcpp::List fastsvd_float32_cpp(SEXP ASEXP, int k, int backend, int svd_method, int rsvd_oversample, int rsvd_power, int seed, bool left_only);
RcppExport SEXP _fastPLS_fastsvd_float32_cpp(SEXP ASEXPSEXP, SEXP kSEXP, SEXP backendSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP seedSEXP, SEXP left_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ASEXP(ASEXPSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type left_only(left_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(fastsvd_float32_cpp(ASEXP, k, backend, svd_method, rsvd_oversample, rsvd_power, seed, left_only));
    return rcpp_result_gen;
END_RCPP
}
// pls_float32_cpu_cpp
Rcpp::List pls_float32_cpu_cpp(SEXP XtrainSEXP, SEXP YtrainSEXP, arma::ivec ncomp, int scaling, bool fit, int method, int backend, int svd_method, int rsvd_oversample, int rsvd_power, int seed);
RcppExport SEXP _fastPLS_pls_float32_cpu_cpp(SEXP XtrainSEXPSEXP, SEXP YtrainSEXPSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP methodSEXP, SEXP backendSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XtrainSEXP(XtrainSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YtrainSEXP(YtrainSEXPSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_float32_cpu_cpp(XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_float32_labels_cpp
Rcpp::List pls_float32_labels_cpp(SEXP XtrainSEXP, const Rcpp::IntegerVector& labels, int n_classes, arma::ivec ncomp, int scaling, bool fit, int method, int backend, int svd_method, int rsvd_oversample, int rsvd_power, int seed);
RcppExport SEXP _fastPLS_pls_float32_labels_cpp(SEXP XtrainSEXPSEXP, SEXP labelsSEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP methodSEXP, SEXP backendSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XtrainSEXP(XtrainSEXPSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_float32_labels_cpp(XtrainSEXP, labels, n_classes, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed));
    return rcpp_result_gen;
END_RCPP
}
// float32_argmax_cpp
Rcpp::IntegerVector float32_argmax_cpp(SEXP scoresSEXP);
RcppExport SEXP _fastPLS_float32_argmax_cpp(SEXP scoresSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type scoresSEXP(scoresSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(float32_argmax_cpp(scoresSEXP));
    return rcpp_result_gen;
END_RCPP
}
// float32_topk_cpp
Rcpp::List float32_topk_cpp(SEXP scoresSEXP, int top);
RcppExport SEXP _fastPLS_float32_topk_cpp(SEXP scoresSEXPSEXP, SEXP topSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type scoresSEXP(scoresSEXPSEXP);
    Rcpp::traits::input_parameter< int >::type top(topSEXP);
    rcpp_result_gen = Rcpp::wrap(float32_topk_cpp(scoresSEXP, top));
    return rcpp_result_gen;
END_RCPP
}
// lda_cuda_native_available
bool lda_cuda_native_available();
RcppExport SEXP _fastPLS_lda_cuda_native_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lda_cuda_native_available());
    return rcpp_result_gen;
END_RCPP
}
// cuda_matrix_multiply
arma::mat cuda_matrix_multiply(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _fastPLS_cuda_matrix_multiply(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(cuda_matrix_multiply(A, B));
    return rcpp_result_gen;
END_RCPP
}
// lda_train_prefix_cpp
Rcpp::List lda_train_prefix_cpp(const arma::mat& Ttrain, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp, double ridge);
RcppExport SEXP _fastPLS_lda_train_prefix_cpp(SEXP TtrainSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttrain(TtrainSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_train_prefix_cpp(Ttrain, y, n_classes, ncomp, ridge));
    return rcpp_result_gen;
END_RCPP
}
// lda_train_moments_prefix_cpp
Rcpp::List lda_train_moments_prefix_cpp(const arma::mat& gram, const arma::mat& class_sums, const arma::vec& counts, int n, const Rcpp::IntegerVector& ncomp);
RcppExport SEXP _fastPLS_lda_train_moments_prefix_cpp(SEXP gramSEXP, SEXP class_sumsSEXP, SEXP countsSEXP, SEXP nSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type gram(gramSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type class_sums(class_sumsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_train_moments_prefix_cpp(gram, class_sums, counts, n, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// lda_project_train_prefix_cpp
Rcpp::List lda_project_train_prefix_cpp(const arma::mat& Xtrain, const arma::mat& R, const arma::rowvec& offset, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp, double ridge);
RcppExport SEXP _fastPLS_lda_project_train_prefix_cpp(SEXP XtrainSEXP, SEXP RSEXP, SEXP offsetSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_project_train_prefix_cpp(Xtrain, R, offset, y, n_classes, ncomp, ridge));
    return rcpp_result_gen;
END_RCPP
}
// lda_train_prefix_cuda
Rcpp::List lda_train_prefix_cuda(const arma::mat& Ttrain, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp, double ridge);
RcppExport SEXP _fastPLS_lda_train_prefix_cuda(SEXP TtrainSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttrain(TtrainSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_train_prefix_cuda(Ttrain, y, n_classes, ncomp, ridge));
    return rcpp_result_gen;
END_RCPP
}
// lda_project_train_prefix_cuda
Rcpp::List lda_project_train_prefix_cuda(const arma::mat& Xtrain, const arma::mat& R, const arma::rowvec& offset, const Rcpp::IntegerVector& y, int n_classes, const Rcpp::IntegerVector& ncomp, double ridge);
RcppExport SEXP _fastPLS_lda_project_train_prefix_cuda(SEXP XtrainSEXP, SEXP RSEXP, SEXP offsetSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_project_train_prefix_cuda(Xtrain, R, offset, y, n_classes, ncomp, ridge));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_cpp
Rcpp::List lda_predict_cpp(const arma::mat& Ttest, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_predict_cpp(SEXP TtestSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest(TtestSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_cpp(Ttest, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_labels_cpp
Rcpp::IntegerVector lda_predict_labels_cpp(const arma::mat& Ttest, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_predict_labels_cpp(SEXP TtestSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest(TtestSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_labels_cpp(Ttest, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_project_predict_labels_cpp
Rcpp::IntegerVector lda_project_predict_labels_cpp(const arma::mat& Xtest, const arma::mat& R, const arma::rowvec& offset, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_project_predict_labels_cpp(SEXP XtestSEXP, SEXP RSEXP, SEXP offsetSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_project_predict_labels_cpp(Xtest, R, offset, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_cuda
Rcpp::List lda_predict_cuda(const arma::mat& Ttest, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_predict_cuda(SEXP TtestSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest(TtestSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_cuda(Ttest, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_predict_labels_cuda
Rcpp::IntegerVector lda_predict_labels_cuda(const arma::mat& Ttest, const Rcpp::List& lda);
RcppExport SEXP _fastPLS_lda_predict_labels_cuda(SEXP TtestSEXP, SEXP ldaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ttest(TtestSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_predict_labels_cuda(Ttest, lda));
    return rcpp_result_gen;
END_RCPP
}
// lda_project_predict_cuda
Rcpp::List lda_project_predict_cuda(const arma::mat& Xtest, const arma::mat& R, const arma::rowvec& offset, const Rcpp::List& lda, bool return_scores);
RcppExport SEXP _fastPLS_lda_project_predict_cuda(SEXP XtestSEXP, SEXP RSEXP, SEXP offsetSEXP, SEXP ldaSEXP, SEXP return_scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type lda(ldaSEXP);
    Rcpp::traits::input_parameter< bool >::type return_scores(return_scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(lda_project_predict_cuda(Xtest, R, offset, lda, return_scores));
    return rcpp_result_gen;
END_RCPP
}
// truncated_svd_debug
Rcpp::List truncated_svd_debug(const arma::mat& A, int k, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, bool left_only);
RcppExport SEXP _fastPLS_truncated_svd_debug(SEXP ASEXP, SEXP kSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP left_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type left_only(left_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(truncated_svd_debug(A, k, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, left_only));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2
List pls_model2(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2_fast
List pls_model2_fast(SEXP XtrainSEXP, SEXP YtrainSEXP, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2_fast(SEXP XtrainSEXPSEXP, SEXP YtrainSEXPSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XtrainSEXP(XtrainSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YtrainSEXP(YtrainSEXPSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2_fast(XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_labels_cpp
List pls_labels_cpp(SEXP XtrainSEXP, const Rcpp::IntegerVector& labels, int n_classes, arma::ivec ncomp, int scaling, bool fit, int method, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_labels_cpp(SEXP XtrainSEXPSEXP, SEXP labelsSEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP methodSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XtrainSEXP(XtrainSEXPSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_labels_cpp(XtrainSEXP, labels, n_classes, ncomp, scaling, fit, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2_fast_gpu
List pls_model2_fast_gpu(SEXP XtrainSEXP, SEXP YtrainSEXP, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2_fast_gpu(SEXP XtrainSEXPSEXP, SEXP YtrainSEXPSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XtrainSEXP(XtrainSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YtrainSEXP(YtrainSEXPSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2_fast_gpu(XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2_fast_gpu_labels
List pls_model2_fast_gpu_labels(SEXP XtrainSEXP, Rcpp::IntegerVector y, int n_classes, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model2_fast_gpu_labels(SEXP XtrainSEXPSEXP, SEXP ySEXP, SEXP n_classesSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XtrainSEXP(XtrainSEXPSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2_fast_gpu_labels(XtrainSEXP, y, n_classes, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_predict
List pls_predict(List& model, SEXP XtestSEXP, bool proj);
RcppExport SEXP _fastPLS_pls_predict(SEXP modelSEXP, SEXP XtestSEXPSEXP, SEXP projSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type XtestSEXP(XtestSEXPSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_predict(model, XtestSEXP, proj));
    return rcpp_result_gen;
END_RCPP
}
// pls_predict_flash_cuda
List pls_predict_flash_cuda(List& model, arma::mat Xtest, bool proj);
RcppExport SEXP _fastPLS_pls_predict_flash_cuda(SEXP modelSEXP, SEXP XtestSEXP, SEXP projSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_predict_flash_cuda(model, Xtest, proj));
    return rcpp_result_gen;
END_RCPP
}
// pls_predict_flash_cpu
List pls_predict_flash_cpu(List& model, SEXP XtestSEXP, bool proj, int block_size);
RcppExport SEXP _fastPLS_pls_predict_flash_cpu(SEXP modelSEXP, SEXP XtestSEXPSEXP, SEXP projSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type XtestSEXP(XtestSEXPSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_predict_flash_cpu(model, XtestSEXP, proj, block_size));
    return rcpp_result_gen;
END_RCPP
}
// pls_class_predict_topk_cpp
List pls_class_predict_topk_cpp(List& model, arma::mat Xtest, int top_k, bool proj, int block_size);
RcppExport SEXP _fastPLS_pls_class_predict_topk_cpp(SEXP modelSEXP, SEXP XtestSEXP, SEXP top_kSEXP, SEXP projSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_class_predict_topk_cpp(model, Xtest, top_k, proj, block_size));
    return rcpp_result_gen;
END_RCPP
}
// pls_class_predict_topk_cuda
List pls_class_predict_topk_cuda(List& model, arma::mat Xtest, int top_k, bool proj);
RcppExport SEXP _fastPLS_pls_class_predict_topk_cuda(SEXP modelSEXP, SEXP XtestSEXP, SEXP top_kSEXP, SEXP projSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< int >::type top_k(top_kSEXP);
    Rcpp::traits::input_parameter< bool >::type proj(projSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_class_predict_topk_cuda(model, Xtest, top_k, proj));
    return rcpp_result_gen;
END_RCPP
}
// kernel_matrix_cpp
arma::mat kernel_matrix_cpp(const arma::mat& X1, const arma::mat& X2, const int kernel, const double gamma, const int degree, const double coef0);
RcppExport SEXP _fastPLS_kernel_matrix_cpp(SEXP X1SEXP, SEXP X2SEXP, SEXP kernelSEXP, SEXP gammaSEXP, SEXP degreeSEXP, SEXP coef0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const double >::type coef0(coef0SEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_matrix_cpp(X1, X2, kernel, gamma, degree, coef0));
    return rcpp_result_gen;
END_RCPP
}
// center_kernel_train_cpp
Rcpp::List center_kernel_train_cpp(const arma::mat& K);
RcppExport SEXP _fastPLS_center_kernel_train_cpp(SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(center_kernel_train_cpp(K));
    return rcpp_result_gen;
END_RCPP
}
// center_kernel_test_cpp
arma::mat center_kernel_test_cpp(const arma::mat& Ktest, const arma::rowvec& train_col_means, const double train_grand_mean);
RcppExport SEXP _fastPLS_center_kernel_test_cpp(SEXP KtestSEXP, SEXP train_col_meansSEXP, SEXP train_grand_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ktest(KtestSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type train_col_means(train_col_meansSEXP);
    Rcpp::traits::input_parameter< const double >::type train_grand_mean(train_grand_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(center_kernel_test_cpp(Ktest, train_col_means, train_grand_mean));
    return rcpp_result_gen;
END_RCPP
}
// opls_filter_cpp
Rcpp::List opls_filter_cpp(arma::mat X, arma::mat Y, const int north, const int scaling);
RcppExport SEXP _fastPLS_opls_filter_cpp(SEXP XSEXP, SEXP YSEXP, SEXP northSEXP, SEXP scalingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int >::type north(northSEXP);
    Rcpp::traits::input_parameter< const int >::type scaling(scalingSEXP);
    rcpp_result_gen = Rcpp::wrap(opls_filter_cpp(X, Y, north, scaling));
    return rcpp_result_gen;
END_RCPP
}
// opls_filter_labels_cpp
Rcpp::List opls_filter_labels_cpp(arma::mat X, const Rcpp::IntegerVector& labels, const int n_classes, const int north, const int scaling);
RcppExport SEXP _fastPLS_opls_filter_labels_cpp(SEXP XSEXP, SEXP labelsSEXP, SEXP n_classesSEXP, SEXP northSEXP, SEXP scalingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< const int >::type north(northSEXP);
    Rcpp::traits::input_parameter< const int >::type scaling(scalingSEXP);
    rcpp_result_gen = Rcpp::wrap(opls_filter_labels_cpp(X, labels, n_classes, north, scaling));
    return rcpp_result_gen;
END_RCPP
}
// opls_apply_filter_cpp
arma::mat opls_apply_filter_cpp(arma::mat X, const arma::rowvec& mX, const arma::rowvec& vX, const arma::mat& W_orth, const arma::mat& P_orth);
RcppExport SEXP _fastPLS_opls_apply_filter_cpp(SEXP XSEXP, SEXP mXSEXP, SEXP vXSEXP, SEXP W_orthSEXP, SEXP P_orthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W_orth(W_orthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P_orth(P_orthSEXP);
    rcpp_result_gen = Rcpp::wrap(opls_apply_filter_cpp(X, mX, vX, W_orth, P_orth));
    return rcpp_result_gen;
END_RCPP
}
// single_pls_cv_cpp
List single_pls_cv_cpp(arma::mat Xdata, arma::mat Ydata, arma::ivec constrain, arma::ivec ncomp, int scaling, int kfold, int method, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_single_pls_cv_cpp(SEXP XdataSEXP, SEXP YdataSEXP, SEXP constrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP kfoldSEXP, SEXP methodSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xdata(XdataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ydata(YdataSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type kfold(kfoldSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(single_pls_cv_cpp(Xdata, Ydata, constrain, ncomp, scaling, kfold, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1
List pls_model1(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model1(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1_rsvd_xprod_precision
List pls_model1_rsvd_xprod_precision(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, int xprod_precision);
RcppExport SEXP _fastPLS_pls_model1_rsvd_xprod_precision(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP xprod_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type xprod_precision(xprod_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1_rsvd_xprod_precision(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision));
    return rcpp_result_gen;
END_RCPP
}
// pls_model2_fast_rsvd_xprod_precision
List pls_model2_fast_rsvd_xprod_precision(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, int xprod_precision);
RcppExport SEXP _fastPLS_pls_model2_fast_rsvd_xprod_precision(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP xprod_precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type xprod_precision(xprod_precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model2_fast_rsvd_xprod_precision(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1_gpu
List pls_model1_gpu(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model1_gpu(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1_gpu(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_model1_gpu_implicit_xprod
List pls_model1_gpu_implicit_xprod(arma::mat Xtrain, arma::mat Ytrain, arma::ivec ncomp, int scaling, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed);
RcppExport SEXP _fastPLS_pls_model1_gpu_implicit_xprod(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_model1_gpu_implicit_xprod(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed));
    return rcpp_result_gen;
END_RCPP
}
// pls_lda_gpu_native
List pls_lda_gpu_native(arma::mat Xtrain, arma::mat Ytrain, arma::ivec y, arma::mat Xtest, arma::ivec ncomp, int n_classes, int method, int scaling, bool xprod, bool fit, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, double lda_ridge);
RcppExport SEXP _fastPLS_pls_lda_gpu_native(SEXP XtrainSEXP, SEXP YtrainSEXP, SEXP ySEXP, SEXP XtestSEXP, SEXP ncompSEXP, SEXP n_classesSEXP, SEXP methodSEXP, SEXP scalingSEXP, SEXP xprodSEXP, SEXP fitSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP lda_ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ytrain(YtrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type n_classes(n_classesSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type xprod(xprodSEXP);
    Rcpp::traits::input_parameter< bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type lda_ridge(lda_ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_lda_gpu_native(Xtrain, Ytrain, y, Xtest, ncomp, n_classes, method, scaling, xprod, fit, rsvd_oversample, rsvd_power, svds_tol, seed, lda_ridge));
    return rcpp_result_gen;
END_RCPP
}
// pls_cv_predict_compiled
List pls_cv_predict_compiled(SEXP Xdata, SEXP Ydata, arma::ivec constrain, arma::ivec ncomp, int scaling, int kfold, int method, int backend, int svd_method, int rsvd_oversample, int rsvd_power, double svds_tol, int seed, bool classification, int n_response, bool xprod, int opls_north, bool return_scores, arma::mat class_codes, int classifier, double lda_ridge, bool store_predictions, int metric_id);
RcppExport SEXP _fastPLS_pls_cv_predict_compiled(SEXP XdataSEXP, SEXP YdataSEXP, SEXP constrainSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP kfoldSEXP, SEXP methodSEXP, SEXP backendSEXP, SEXP svd_methodSEXP, SEXP rsvd_oversampleSEXP, SEXP rsvd_powerSEXP, SEXP svds_tolSEXP, SEXP seedSEXP, SEXP classificationSEXP, SEXP n_responseSEXP, SEXP xprodSEXP, SEXP opls_northSEXP, SEXP return_scoresSEXP, SEXP class_codesSEXP, SEXP classifierSEXP, SEXP lda_ridgeSEXP, SEXP store_predictionsSEXP, SEXP metric_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Xdata(XdataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Ydata(YdataSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type constrain(constrainSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type kfold(kfoldSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< int >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_oversample(rsvd_oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type rsvd_power(rsvd_powerSEXP);
    Rcpp::traits::input_parameter< double >::type svds_tol(svds_tolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type classification(classificationSEXP);
    Rcpp::traits::input_parameter< int >::type n_response(n_responseSEXP);
    Rcpp::traits::input_parameter< bool >::type xprod(xprodSEXP);
    Rcpp::traits::input_parameter< int >::type opls_north(opls_northSEXP);
    Rcpp::traits::input_parameter< bool >::type return_scores(return_scoresSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type class_codes(class_codesSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    Rcpp::traits::input_parameter< double >::type lda_ridge(lda_ridgeSEXP);
    Rcpp::traits::input_parameter< bool >::type store_predictions(store_predictionsSEXP);
    Rcpp::traits::input_parameter< int >::type metric_id(metric_idSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_cv_predict_compiled(Xdata, Ydata, constrain, ncomp, scaling, kfold, method, backend, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, classification, n_response, xprod, opls_north, return_scores, class_codes, classifier, lda_ridge, store_predictions, metric_id));
    return rcpp_result_gen;
END_RCPP
}
// metal_resident_simpls_fit_cpp
Rcpp::List metal_resident_simpls_fit_cpp(SEXP X, SEXP Y, SEXP labels, int classes, int ncomp, int scaling, int oversample, int power, int seed, int method, int north, int kernel, double gamma, int degree, double coefficient);
RcppExport SEXP _fastPLS_metal_resident_simpls_fit_cpp(SEXP XSEXP, SEXP YSEXP, SEXP labelsSEXP, SEXP classesSEXP, SEXP ncompSEXP, SEXP scalingSEXP, SEXP oversampleSEXP, SEXP powerSEXP, SEXP seedSEXP, SEXP methodSEXP, SEXP northSEXP, SEXP kernelSEXP, SEXP gammaSEXP, SEXP degreeSEXP, SEXP coefficientSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type classes(classesSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< int >::type oversample(oversampleSEXP);
    Rcpp::traits::input_parameter< int >::type power(powerSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type north(northSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type coefficient(coefficientSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_resident_simpls_fit_cpp(X, Y, labels, classes, ncomp, scaling, oversample, power, seed, method, north, kernel, gamma, degree, coefficient));
    return rcpp_result_gen;
END_RCPP
}
// metal_resident_export_cpp
SEXP metal_resident_export_cpp(Rcpp::List object, int field);
RcppExport SEXP _fastPLS_metal_resident_export_cpp(SEXP objectSEXP, SEXP fieldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< int >::type field(fieldSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_resident_export_cpp(object, field));
    return rcpp_result_gen;
END_RCPP
}
// metal_resident_compact_cpp
void metal_resident_compact_cpp(Rcpp::List object, bool prepare_lda);
RcppExport SEXP _fastPLS_metal_resident_compact_cpp(SEXP objectSEXP, SEXP prepare_ldaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< bool >::type prepare_lda(prepare_ldaSEXP);
    metal_resident_compact_cpp(object, prepare_lda);
    return R_NilValue;
END_RCPP
}
// metal_resident_predict_path_cpp
SEXP metal_resident_predict_path_cpp(Rcpp::List object, SEXP X, Rcpp::IntegerVector ncomp, int classifier);
RcppExport SEXP _fastPLS_metal_resident_predict_path_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP, SEXP classifierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_resident_predict_path_cpp(object, X, ncomp, classifier));
    return rcpp_result_gen;
END_RCPP
}
// metal_resident_project_cpp
SEXP metal_resident_project_cpp(Rcpp::List object, SEXP X, int ncomp);
RcppExport SEXP _fastPLS_metal_resident_project_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_resident_project_cpp(object, X, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// metal_resident_classify_path_cpp
Rcpp::IntegerVector metal_resident_classify_path_cpp(Rcpp::List object, SEXP X, Rcpp::IntegerVector ncomp, int top, int classifier);
RcppExport SEXP _fastPLS_metal_resident_classify_path_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP, SEXP topSEXP, SEXP classifierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type top(topSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_resident_classify_path_cpp(object, X, ncomp, top, classifier));
    return rcpp_result_gen;
END_RCPP
}
// metal_resident_classify_response_path_cpp
Rcpp::List metal_resident_classify_response_path_cpp(Rcpp::List object, SEXP X, Rcpp::IntegerVector ncomp, int top, int classifier);
RcppExport SEXP _fastPLS_metal_resident_classify_response_path_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP ncompSEXP, SEXP topSEXP, SEXP classifierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type top(topSEXP);
    Rcpp::traits::input_parameter< int >::type classifier(classifierSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_resident_classify_response_path_cpp(object, X, ncomp, top, classifier));
    return rcpp_result_gen;
END_RCPP
}
// metal_resident_response_sums_cpp
SEXP metal_resident_response_sums_cpp(Rcpp::List object, SEXP X, SEXP Y, SEXP labels, int ncomp);
RcppExport SEXP _fastPLS_metal_resident_response_sums_cpp(SEXP objectSEXP, SEXP XSEXP, SEXP YSEXP, SEXP labelsSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_resident_response_sums_cpp(object, X, Y, labels, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// metal_xprod_workspace_cpp
SEXP metal_xprod_workspace_cpp(const arma::mat& X, const arma::mat& Y);
RcppExport SEXP _fastPLS_metal_xprod_workspace_cpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_xprod_workspace_cpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// metal_xprod_workspace_multiply_cpp
arma::mat metal_xprod_workspace_multiply_cpp(SEXP workspace, const arma::mat& B, bool transpose);
RcppExport SEXP _fastPLS_metal_xprod_workspace_multiply_cpp(SEXP workspaceSEXP, SEXP BSEXP, SEXP transposeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type workspace(workspaceSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< bool >::type transpose(transposeSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_xprod_workspace_multiply_cpp(workspace, B, transpose));
    return rcpp_result_gen;
END_RCPP
}
// metal_xprod_workspace_release_cpp
void metal_xprod_workspace_release_cpp(SEXP workspace);
RcppExport SEXP _fastPLS_metal_xprod_workspace_release_cpp(SEXP workspaceSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< SEXP >::type workspace(workspaceSEXP);
    metal_xprod_workspace_release_cpp(workspace);
    return R_NilValue;
END_RCPP
}
// metal_xprod_rsvd_cpp
Rcpp::List metal_xprod_rsvd_cpp(const arma::mat& X, const arma::mat& Y, const arma::mat& omega, int target, int power, bool left_only);
RcppExport SEXP _fastPLS_metal_xprod_rsvd_cpp(SEXP XSEXP, SEXP YSEXP, SEXP omegaSEXP, SEXP targetSEXP, SEXP powerSEXP, SEXP left_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< int >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type power(powerSEXP);
    Rcpp::traits::input_parameter< bool >::type left_only(left_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(metal_xprod_rsvd_cpp(X, Y, omega, target, power, left_only));
    return rcpp_result_gen;
END_RCPP
}
// metal_matrix_multiply_cpp
arma::mat metal_matrix_multiply_cpp(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _fastPLS_metal_matrix_multiply_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_matrix_multiply_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// metal_crossprod_cpp
arma::mat metal_crossprod_cpp(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _fastPLS_metal_crossprod_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_crossprod_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// metal_simpls_resident_cpp
Rcpp::List metal_simpls_resident_cpp(const arma::mat& X, const arma::mat& Y, int ncomp, int power_iters, int seed);
RcppExport SEXP _fastPLS_metal_simpls_resident_cpp(SEXP XSEXP, SEXP YSEXP, SEXP ncompSEXP, SEXP power_itersSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    Rcpp::traits::input_parameter< int >::type power_iters(power_itersSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(metal_simpls_resident_cpp(X, Y, ncomp, power_iters, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastPLS_cuda_resident_project_cpp", (DL_FUNC) &_fastPLS_cuda_resident_project_cpp, 3},
    {"_fastPLS_cuda_resident_response_sums_cpp", (DL_FUNC) &_fastPLS_cuda_resident_response_sums_cpp, 5},
    {"_fastPLS_cuda_resident_simpls_fit_cpp", (DL_FUNC) &_fastPLS_cuda_resident_simpls_fit_cpp, 17},
    {"_fastPLS_cuda_resident_export_cpp", (DL_FUNC) &_fastPLS_cuda_resident_export_cpp, 4},
    {"_fastPLS_cuda_resident_compact_cpp", (DL_FUNC) &_fastPLS_cuda_resident_compact_cpp, 2},
    {"_fastPLS_cuda_resident_classify_cpp", (DL_FUNC) &_fastPLS_cuda_resident_classify_cpp, 5},
    {"_fastPLS_cuda_resident_classify_path_cpp", (DL_FUNC) &_fastPLS_cuda_resident_classify_path_cpp, 5},
    {"_fastPLS_cuda_resident_classify_response_path_cpp", (DL_FUNC) &_fastPLS_cuda_resident_classify_response_path_cpp, 5},
    {"_fastPLS_cuda_resident_simpls_predict_cpp", (DL_FUNC) &_fastPLS_cuda_resident_simpls_predict_cpp, 4},
    {"_fastPLS_cuda_resident_predict_path_cpp", (DL_FUNC) &_fastPLS_cuda_resident_predict_path_cpp, 4},
    {"_fastPLS_rsvd_audit_reset_debug", (DL_FUNC) &_fastPLS_rsvd_audit_reset_debug, 0},
    {"_fastPLS_rsvd_audit_summary_debug", (DL_FUNC) &_fastPLS_rsvd_audit_summary_debug, 0},
    {"_fastPLS_label_crossprod_scaled_cpp", (DL_FUNC) &_fastPLS_label_crossprod_scaled_cpp, 4},
    {"_fastPLS_float32_sweep_cols_cpp", (DL_FUNC) &_fastPLS_float32_sweep_cols_cpp, 3},
    {"_fastPLS_float32_standardize_cpp", (DL_FUNC) &_fastPLS_float32_standardize_cpp, 3},
    {"_fastPLS_kernel_matrix_float32_cpp", (DL_FUNC) &_fastPLS_kernel_matrix_float32_cpp, 7},
    {"_fastPLS_center_kernel_train_float32_cpp", (DL_FUNC) &_fastPLS_center_kernel_train_float32_cpp, 1},
    {"_fastPLS_center_kernel_test_float32_cpp", (DL_FUNC) &_fastPLS_center_kernel_test_float32_cpp, 3},
    {"_fastPLS_opls_filter_float32_cpp", (DL_FUNC) &_fastPLS_opls_filter_float32_cpp, 9},
    {"_fastPLS_opls_filter_float32_labels_cpp", (DL_FUNC) &_fastPLS_opls_filter_float32_labels_cpp, 10},
    {"_fastPLS_opls_apply_filter_float32_cpp", (DL_FUNC) &_fastPLS_opls_apply_filter_float32_cpp, 6},
    {"_fastPLS_lda_train_prefix_float32_cpp", (DL_FUNC) &_fastPLS_lda_train_prefix_float32_cpp, 4},
    {"_fastPLS_lda_predict_float32_cpp", (DL_FUNC) &_fastPLS_lda_predict_float32_cpp, 3},
    {"_fastPLS_lda_train_prefix_float32_cuda", (DL_FUNC) &_fastPLS_lda_train_prefix_float32_cuda, 4},
    {"_fastPLS_lda_predict_float32_cuda", (DL_FUNC) &_fastPLS_lda_predict_float32_cuda, 3},
    {"_fastPLS_cuda_float32_rsvd_sample_cpp", (DL_FUNC) &_fastPLS_cuda_float32_rsvd_sample_cpp, 4},
    {"_fastPLS_cpu_float32_matrix_multiply_cpp", (DL_FUNC) &_fastPLS_cpu_float32_matrix_multiply_cpp, 4},
    {"_fastPLS_metal_float32_matrix_multiply_cpp", (DL_FUNC) &_fastPLS_metal_float32_matrix_multiply_cpp, 4},
    {"_fastPLS_metal_float32_rsvd_sample_cpp", (DL_FUNC) &_fastPLS_metal_float32_rsvd_sample_cpp, 4},
    {"_fastPLS_fastsvd_float32_cpp", (DL_FUNC) &_fastPLS_fastsvd_float32_cpp, 8},
    {"_fastPLS_pls_float32_cpu_cpp", (DL_FUNC) &_fastPLS_pls_float32_cpu_cpp, 11},
    {"_fastPLS_pls_float32_labels_cpp", (DL_FUNC) &_fastPLS_pls_float32_labels_cpp, 12},
    {"_fastPLS_float32_argmax_cpp", (DL_FUNC) &_fastPLS_float32_argmax_cpp, 1},
    {"_fastPLS_float32_topk_cpp", (DL_FUNC) &_fastPLS_float32_topk_cpp, 2},
    {"_fastPLS_has_cuda", (DL_FUNC) &_fastPLS_has_cuda, 0},
    {"_fastPLS_lda_cuda_native_available", (DL_FUNC) &_fastPLS_lda_cuda_native_available, 0},
    {"_fastPLS_cuda_matrix_multiply", (DL_FUNC) &_fastPLS_cuda_matrix_multiply, 2},
    {"_fastPLS_lda_train_prefix_cpp", (DL_FUNC) &_fastPLS_lda_train_prefix_cpp, 5},
    {"_fastPLS_lda_train_moments_prefix_cpp", (DL_FUNC) &_fastPLS_lda_train_moments_prefix_cpp, 5},
    {"_fastPLS_lda_project_train_prefix_cpp", (DL_FUNC) &_fastPLS_lda_project_train_prefix_cpp, 7},
    {"_fastPLS_lda_train_prefix_cuda", (DL_FUNC) &_fastPLS_lda_train_prefix_cuda, 5},
    {"_fastPLS_lda_project_train_prefix_cuda", (DL_FUNC) &_fastPLS_lda_project_train_prefix_cuda, 7},
    {"_fastPLS_lda_predict_cpp", (DL_FUNC) &_fastPLS_lda_predict_cpp, 2},
    {"_fastPLS_lda_predict_labels_cpp", (DL_FUNC) &_fastPLS_lda_predict_labels_cpp, 2},
    {"_fastPLS_lda_project_predict_labels_cpp", (DL_FUNC) &_fastPLS_lda_project_predict_labels_cpp, 4},
    {"_fastPLS_lda_predict_cuda", (DL_FUNC) &_fastPLS_lda_predict_cuda, 2},
    {"_fastPLS_lda_predict_labels_cuda", (DL_FUNC) &_fastPLS_lda_predict_labels_cuda, 2},
    {"_fastPLS_lda_project_predict_cuda", (DL_FUNC) &_fastPLS_lda_project_predict_cuda, 5},
    {"_fastPLS_truncated_svd_debug", (DL_FUNC) &_fastPLS_truncated_svd_debug, 8},
    {"_fastPLS_pls_model2", (DL_FUNC) &_fastPLS_pls_model2, 10},
    {"_fastPLS_pls_model2_fast", (DL_FUNC) &_fastPLS_pls_model2_fast, 10},
    {"_fastPLS_pls_labels_cpp", (DL_FUNC) &_fastPLS_pls_labels_cpp, 12},
    {"_fastPLS_pls_model2_fast_gpu", (DL_FUNC) &_fastPLS_pls_model2_fast_gpu, 10},
    {"_fastPLS_pls_model2_fast_gpu_labels", (DL_FUNC) &_fastPLS_pls_model2_fast_gpu_labels, 11},
    {"_fastPLS_pls_predict", (DL_FUNC) &_fastPLS_pls_predict, 3},
    {"_fastPLS_pls_predict_flash_cuda", (DL_FUNC) &_fastPLS_pls_predict_flash_cuda, 3},
    {"_fastPLS_pls_predict_flash_cpu", (DL_FUNC) &_fastPLS_pls_predict_flash_cpu, 4},
    {"_fastPLS_pls_class_predict_topk_cpp", (DL_FUNC) &_fastPLS_pls_class_predict_topk_cpp, 5},
    {"_fastPLS_pls_class_predict_topk_cuda", (DL_FUNC) &_fastPLS_pls_class_predict_topk_cuda, 4},
    {"_fastPLS_kernel_matrix_cpp", (DL_FUNC) &_fastPLS_kernel_matrix_cpp, 6},
    {"_fastPLS_center_kernel_train_cpp", (DL_FUNC) &_fastPLS_center_kernel_train_cpp, 1},
    {"_fastPLS_center_kernel_test_cpp", (DL_FUNC) &_fastPLS_center_kernel_test_cpp, 3},
    {"_fastPLS_opls_filter_cpp", (DL_FUNC) &_fastPLS_opls_filter_cpp, 4},
    {"_fastPLS_opls_filter_labels_cpp", (DL_FUNC) &_fastPLS_opls_filter_labels_cpp, 5},
    {"_fastPLS_opls_apply_filter_cpp", (DL_FUNC) &_fastPLS_opls_apply_filter_cpp, 5},
    {"_fastPLS_single_pls_cv_cpp", (DL_FUNC) &_fastPLS_single_pls_cv_cpp, 12},
    {"_fastPLS_pls_model1", (DL_FUNC) &_fastPLS_pls_model1, 10},
    {"_fastPLS_pls_model1_rsvd_xprod_precision", (DL_FUNC) &_fastPLS_pls_model1_rsvd_xprod_precision, 10},
    {"_fastPLS_pls_model2_fast_rsvd_xprod_precision", (DL_FUNC) &_fastPLS_pls_model2_fast_rsvd_xprod_precision, 10},
    {"_fastPLS_pls_model1_gpu", (DL_FUNC) &_fastPLS_pls_model1_gpu, 10},
    {"_fastPLS_pls_model1_gpu_implicit_xprod", (DL_FUNC) &_fastPLS_pls_model1_gpu_implicit_xprod, 9},
    {"_fastPLS_pls_lda_gpu_native", (DL_FUNC) &_fastPLS_pls_lda_gpu_native, 15},
    {"_fastPLS_pls_cv_predict_compiled", (DL_FUNC) &_fastPLS_pls_cv_predict_compiled, 23},
    {"_fastPLS_metal_resident_simpls_fit_cpp", (DL_FUNC) &_fastPLS_metal_resident_simpls_fit_cpp, 15},
    {"_fastPLS_metal_resident_export_cpp", (DL_FUNC) &_fastPLS_metal_resident_export_cpp, 2},
    {"_fastPLS_metal_resident_compact_cpp", (DL_FUNC) &_fastPLS_metal_resident_compact_cpp, 2},
    {"_fastPLS_metal_resident_predict_path_cpp", (DL_FUNC) &_fastPLS_metal_resident_predict_path_cpp, 4},
    {"_fastPLS_metal_resident_project_cpp", (DL_FUNC) &_fastPLS_metal_resident_project_cpp, 3},
    {"_fastPLS_metal_resident_classify_path_cpp", (DL_FUNC) &_fastPLS_metal_resident_classify_path_cpp, 5},
    {"_fastPLS_metal_resident_classify_response_path_cpp", (DL_FUNC) &_fastPLS_metal_resident_classify_response_path_cpp, 5},
    {"_fastPLS_metal_resident_response_sums_cpp", (DL_FUNC) &_fastPLS_metal_resident_response_sums_cpp, 5},
    {"_fastPLS_spearman_correlation_cpp", (DL_FUNC) &_fastPLS_spearman_correlation_cpp, 2},
    {"_fastPLS_metal_xprod_workspace_cpp", (DL_FUNC) &_fastPLS_metal_xprod_workspace_cpp, 2},
    {"_fastPLS_metal_xprod_workspace_multiply_cpp", (DL_FUNC) &_fastPLS_metal_xprod_workspace_multiply_cpp, 3},
    {"_fastPLS_metal_xprod_workspace_release_cpp", (DL_FUNC) &_fastPLS_metal_xprod_workspace_release_cpp, 1},
    {"_fastPLS_metal_xprod_rsvd_cpp", (DL_FUNC) &_fastPLS_metal_xprod_rsvd_cpp, 6},
    {"_fastPLS_has_metal", (DL_FUNC) &_fastPLS_has_metal, 0},
    {"_fastPLS_metal_matrix_multiply_cpp", (DL_FUNC) &_fastPLS_metal_matrix_multiply_cpp, 2},
    {"_fastPLS_metal_crossprod_cpp", (DL_FUNC) &_fastPLS_metal_crossprod_cpp, 2},
    {"_fastPLS_metal_simpls_resident_cpp", (DL_FUNC) &_fastPLS_metal_simpls_resident_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastPLS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
