# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

opls_filter_float32_cpp <- function(XSEXP, YSEXP, north, scaling, backend, svd_method, rsvd_oversample, rsvd_power, seed) {
    .Call(`_fastPLS_opls_filter_float32_cpp`, XSEXP, YSEXP, north, scaling, backend, svd_method, rsvd_oversample, rsvd_power, seed)
}

opls_filter_float32_labels_cpp <- function(XSEXP, labels, n_classes, north, scaling, backend, svd_method, rsvd_oversample, rsvd_power, seed) {
    .Call(`_fastPLS_opls_filter_float32_labels_cpp`, XSEXP, labels, n_classes, north, scaling, backend, svd_method, rsvd_oversample, rsvd_power, seed)
}

lda_train_prefix_float32_cuda <- function(TtrainSEXP, y, n_classes, ncomp) {
    .Call(`_fastPLS_lda_train_prefix_float32_cuda`, TtrainSEXP, y, n_classes, ncomp)
}

lda_predict_float32_cuda <- function(TtestSEXP, lda, return_scores = TRUE) {
    .Call(`_fastPLS_lda_predict_float32_cuda`, TtestSEXP, lda, return_scores)
}

fastsvd_float32_cpp <- function(ASEXP, k, backend, svd_method, rsvd_oversample, rsvd_power, seed, left_only = FALSE) {
    .Call(`_fastPLS_fastsvd_float32_cpp`, ASEXP, k, backend, svd_method, rsvd_oversample, rsvd_power, seed, left_only)
}

pls_float32_cpu_cpp <- function(XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed) {
    .Call(`_fastPLS_pls_float32_cpu_cpp`, XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed)
}

pls_float32_labels_cpp <- function(XtrainSEXP, labels, n_classes, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed) {
    .Call(`_fastPLS_pls_float32_labels_cpp`, XtrainSEXP, labels, n_classes, ncomp, scaling, fit, method, backend, svd_method, rsvd_oversample, rsvd_power, seed)
}

lda_train_prefix_cuda <- function(Ttrain, y, n_classes, ncomp, ridge) {
    .Call(`_fastPLS_lda_train_prefix_cuda`, Ttrain, y, n_classes, ncomp, ridge)
}

lda_project_train_prefix_cuda <- function(Xtrain, R, offset, y, n_classes, ncomp, ridge) {
    .Call(`_fastPLS_lda_project_train_prefix_cuda`, Xtrain, R, offset, y, n_classes, ncomp, ridge)
}

lda_predict_cuda <- function(Ttest, lda) {
    .Call(`_fastPLS_lda_predict_cuda`, Ttest, lda)
}

lda_predict_labels_cuda <- function(Ttest, lda) {
    .Call(`_fastPLS_lda_predict_labels_cuda`, Ttest, lda)
}

lda_project_predict_cuda <- function(Xtest, R, offset, lda, return_scores = FALSE) {
    .Call(`_fastPLS_lda_project_predict_cuda`, Xtest, R, offset, lda, return_scores)
}

truncated_svd_debug <- function(A, k, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, left_only) {
    .Call(`_fastPLS_truncated_svd_debug`, A, k, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, left_only)
}

pls_model2 <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model2`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model2_fast <- function(XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model2_fast`, XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_labels_cpp <- function(XtrainSEXP, labels, n_classes, ncomp, scaling, fit, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_labels_cpp`, XtrainSEXP, labels, n_classes, ncomp, scaling, fit, method, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model2_fast_gpu <- function(XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model2_fast_gpu`, XtrainSEXP, YtrainSEXP, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_predict <- function(model, XtestSEXP, proj) {
    .Call(`_fastPLS_pls_predict`, model, XtestSEXP, proj)
}

pls_predict_flash_cuda <- function(model, Xtest, proj) {
    .Call(`_fastPLS_pls_predict_flash_cuda`, model, Xtest, proj)
}

pls_predict_flash_cpu <- function(model, XtestSEXP, proj, block_size) {
    .Call(`_fastPLS_pls_predict_flash_cpu`, model, XtestSEXP, proj, block_size)
}

pls_class_predict_topk_cpp <- function(model, Xtest, top_k, proj, block_size) {
    .Call(`_fastPLS_pls_class_predict_topk_cpp`, model, Xtest, top_k, proj, block_size)
}

pls_class_predict_topk_cuda <- function(model, Xtest, top_k, proj) {
    .Call(`_fastPLS_pls_class_predict_topk_cuda`, model, Xtest, top_k, proj)
}

opls_filter_cpp <- function(X, Y, north, scaling) {
    .Call(`_fastPLS_opls_filter_cpp`, X, Y, north, scaling)
}

opls_filter_labels_cpp <- function(X, labels, n_classes, north, scaling) {
    .Call(`_fastPLS_opls_filter_labels_cpp`, X, labels, n_classes, north, scaling)
}

pls_model1 <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model1`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model1_rsvd_xprod_precision <- function(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision) {
    .Call(`_fastPLS_pls_model1_rsvd_xprod_precision`, Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision)
}

pls_model2_fast_rsvd_xprod_precision <- function(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision) {
    .Call(`_fastPLS_pls_model2_fast_rsvd_xprod_precision`, Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed, xprod_precision)
}

pls_model1_gpu <- function(Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model1_gpu`, Xtrain, Ytrain, ncomp, scaling, fit, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_model1_gpu_implicit_xprod <- function(Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed) {
    .Call(`_fastPLS_pls_model1_gpu_implicit_xprod`, Xtrain, Ytrain, ncomp, scaling, fit, rsvd_oversample, rsvd_power, svds_tol, seed)
}

pls_lda_gpu_native <- function(Xtrain, Ytrain, y, Xtest, ncomp, n_classes, method, scaling, xprod, fit, rsvd_oversample, rsvd_power, svds_tol, seed, lda_ridge) {
    .Call(`_fastPLS_pls_lda_gpu_native`, Xtrain, Ytrain, y, Xtest, ncomp, n_classes, method, scaling, xprod, fit, rsvd_oversample, rsvd_power, svds_tol, seed, lda_ridge)
}

pls_cv_predict_compiled <- function(Xdata, Ydata, constrain, ncomp, scaling, kfold, method, backend, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, classification, n_response, xprod, opls_north, return_scores, class_codes, classifier, lda_ridge, store_predictions, metric_id) {
    .Call(`_fastPLS_pls_cv_predict_compiled`, Xdata, Ydata, constrain, ncomp, scaling, kfold, method, backend, svd_method, rsvd_oversample, rsvd_power, svds_tol, seed, classification, n_response, xprod, opls_north, return_scores, class_codes, classifier, lda_ridge, store_predictions, metric_id)
}

metal_resident_simpls_fit_cpp <- function(X, Y, labels, classes, ncomp, scaling, oversample, power, seed, method = 3L, north = 1L, kernel = 2L, gamma = 1.0, degree = 3L, coefficient = 1.0) {
    .Call(`_fastPLS_metal_resident_simpls_fit_cpp`, X, Y, labels, classes, ncomp, scaling, oversample, power, seed, method, north, kernel, gamma, degree, coefficient)
}

metal_resident_export_cpp <- function(object, field) {
    .Call(`_fastPLS_metal_resident_export_cpp`, object, field)
}

metal_resident_compact_cpp <- function(object, prepare_lda = FALSE) {
    invisible(.Call(`_fastPLS_metal_resident_compact_cpp`, object, prepare_lda))
}

metal_resident_predict_path_cpp <- function(object, X, ncomp, classifier = 0L) {
    .Call(`_fastPLS_metal_resident_predict_path_cpp`, object, X, ncomp, classifier)
}

metal_resident_project_cpp <- function(object, X, ncomp) {
    .Call(`_fastPLS_metal_resident_project_cpp`, object, X, ncomp)
}

metal_resident_classify_path_cpp <- function(object, X, ncomp, top, classifier = 0L) {
    .Call(`_fastPLS_metal_resident_classify_path_cpp`, object, X, ncomp, top, classifier)
}

metal_resident_classify_response_path_cpp <- function(object, X, ncomp, top, classifier = 0L) {
    .Call(`_fastPLS_metal_resident_classify_response_path_cpp`, object, X, ncomp, top, classifier)
}

metal_resident_response_sums_cpp <- function(object, X, Y, labels, ncomp) {
    .Call(`_fastPLS_metal_resident_response_sums_cpp`, object, X, Y, labels, ncomp)
}

metal_xprod_rsvd_cpp <- function(X, Y, omega, target, power, left_only) {
    .Call(`_fastPLS_metal_xprod_rsvd_cpp`, X, Y, omega, target, power, left_only)
}

metal_matrix_multiply_cpp <- function(A, B) {
    .Call(`_fastPLS_metal_matrix_multiply_cpp`, A, B)
}

metal_crossprod_cpp <- function(A, B) {
    .Call(`_fastPLS_metal_crossprod_cpp`, A, B)
}

metal_simpls_resident_cpp <- function(X, Y, ncomp, power_iters = 5L, seed = 1L) {
    .Call(`_fastPLS_metal_simpls_resident_cpp`, X, Y, ncomp, power_iters, seed)
}
